-- CREATION BDD
	CREATE DATABASE pur_beurre CHARACTER SET 'utf8';
	USE pur_beurre;

-- CREATION TABLE CATEGORY
	CREATE TABLE Category (
	Id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR (200) NOT NULL,
	PRIMARY KEY (id)
	)
	ENGINE=INNODB;

-- CREATION TABLE PRODUCT
	CREATE TABLE Product (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR (200) NOT NULL UNIQUE,
	description TEXT,
	url VARCHAR (900) NOT NULL,
	nutrition_grade VARCHAR (5),
	favorites BOOLEAN,
	PRIMARY KEY (id)
	)
	ENGINE=INNODB;

-- CREATION TABLE SHOP
	CREATE TABLE Shop (
	Id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR (200) NOT NULL,
	PRIMARY KEY (id)
	)
	ENGINE=INNODB;

-- CREATION TABLE LINK_PROD_CAT
	CREATE TABLE Link_prod_cat (
	id_category SMALLINT UNSIGNED NOT NULL,
	id_product SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id_category, id_product),
	CONSTRAINT fk_category_id FOREIGN KEY (id_category) REFERENCES Category(id) ON DELETE CASCADE,
	CONSTRAINT fk_product_id FOREIGN KEY (id_product) REFERENCES Product(id) ON DELETE CASCADE
	)
	ENGINE=INNODB;


-- CREATION TABLE LINK_PROD_SHOP
	CREATE TABLE Link_prod_shop (
	id_product SMALLINT UNSIGNED NOT NULL,
	id_shop SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id_product, id_shop),
	CONSTRAINT fk_prod_id FOREIGN KEY (id_product) REFERENCES Product(id) ON DELETE CASCADE,
	CONSTRAINT fk_shop_id FOREIGN KEY (id_shop) REFERENCES Shop(id) ON DELETE CASCADE
	)
	ENGINE=INNODB;

# -- CREATION TABLE USER_PRODUCTS
# 	CREATE TABLE User_products (
# 	name VARCHAR (200) NOT NULL,
# 	description TEXT,
# 	nutrition_grade VARCHAR (5),
# 	shop VARCHAR (200) NOT NULL,
# 	url VARCHAR (900) NOT NULL
# 	)
# 	ENGINE=INNODB;
